export { PHOSPHOR_COLORS, getRGBA, getBrightRGB } from './colors'
export type { RGB } from './colors'
export { drawWaveform } from './waveform'
export { drawLissajous } from './lissajous'
export { drawSpectrum } from './spectrum'
